# Generated by Django 4.2.7 on 2023-12-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('seriya_raqam', models.IntegerField(max_length=6, unique=True)),
                ('fiskal_raqam', models.CharField(max_length=14, unique=True)),
                ('fiskal_belgi', models.IntegerField(max_length=12, unique=True)),
                ('check_raqam', models.IntegerField(max_length=5, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
    ]
