# Generated by Django 4.2.7 on 2023-12-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmodel',
            name='check_raqam',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='checkmodel',
            name='fiskal_belgi',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='checkmodel',
            name='seriya_raqam',
            field=models.IntegerField(unique=True),
        ),
    ]
