# Generated by Django 4.2.7 on 2023-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckApp', '0002_alter_checkmodel_check_raqam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmodel',
            name='korxona_nomi',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
