# Generated by Django 4.2.7 on 2023-12-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckApp', '0003_checkmodel_korxona_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmodel',
            name='money',
            field=models.IntegerField(default=None),
        ),
    ]
